openapi: 3.0.1
info:
  title: CE_API_Proxy
  description: API Definition of CE_API_Proxy
  version: 1.0.0
servers:
- url: http://localhost:8290/ce
- url: https://localhost:8253/ce
paths:
  /:
    get:
      responses:
        default:
          description: Default response
  /students:
    get:
      responses:
        default:
          description: Default response
  /projects:
    get:
      responses:
        default:
          description: Default response
  /staff:
    get:
      responses:
        default:
          description: Default response
  /events:
    get:
      responses:
        default:
          description: Default response
  /news:
    get:
      responses:
        default:
          description: Default response
  /publications:
    get:
      responses:
        default:
          description: Default response
